name: Khoi Api CICD

on: 
  push:
    branches:
    - main

jobs:
  setup-build:
    name: Setup and Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Create .env file
      run: echo "PORT=${{ secrets.PORT }}" >> .env
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t kn11299/khoi-api .
    - name: Push Docker Image
      run: docker push kn11299/khoi-api:latest
  deploy:
    needs: setup-build
    runs-on: self-hosted
    steps:
    - name: Pull Docker Image
      run: docker pull kn11299/khoi-api:latest
    - name: Delete old container
      run: docker rm -f khoi-api-containter
    - name: Run docker container
      run: docker run -d -p 8085:8085 --name khoi-api-containter kn11299/khoi-api:latest